version: '3.8'

services:
  database:
    image: postgres
    container_name: container_melo
    environment:
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: minitwitter
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minitwitter-api
    environment:
      DATABASE_URL: postgres://postgres:supersecret123@database:5432/minitwitter
    ports:
      - "3000:3000"
    depends_on:
      - database
